import type { StorybookConfig } from '@storybook/nextjs-vite'

const config: StorybookConfig = {
  stories: [
    '../src/components/**/*.mdx',
    '../src/components/storybook-starters/**/*.mdx',
    '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)',
  ],
  framework: {
    name: '@storybook/nextjs-vite',
    options: {
      appDirectory: true,
    },
  },
  staticDirs: ['../public'],
  docs: {},
  addons: [
    // Sun/Moon toggle for the manager, preview, and preview background
    'storybook-dark-mode',
    // Story-level theme selector
    '@storybook/addon-themes',
    // Accessibility panel and checks
    '@storybook/addon-a11y',
    // Design reference panel
    {
      name: '@storybook/addon-designs',
      options: {},
    },
    // Link navigation between stories
    '@storybook/addon-links',
    // Autogenerated MDX/React documentation
    {
      name: '@storybook/addon-docs',
      options: {
        sourceLoaderOptions: {
          injectStoryParameters: false,
        },
      },
    },
    // Rendered HTML panel
    '@whitespace/storybook-addon-html',
  ],
}
export default config
